// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nmap.proto

package nmapservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScanRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	PortSpec             string   `protobuf:"bytes,2,opt,name=portSpec,proto3" json:"portSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aaa3a40e8dcfc7a, []int{0}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ScanRequest) GetPortSpec() string {
	if m != nil {
		return m.PortSpec
	}
	return ""
}

type ScanReply struct {
	State                string            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Addresses            []string          `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Hostnames            []string          `protobuf:"bytes,3,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	Ports                []*ScanReply_Port `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScanReply) Reset()         { *m = ScanReply{} }
func (m *ScanReply) String() string { return proto.CompactTextString(m) }
func (*ScanReply) ProtoMessage()    {}
func (*ScanReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aaa3a40e8dcfc7a, []int{1}
}

func (m *ScanReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanReply.Unmarshal(m, b)
}
func (m *ScanReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanReply.Marshal(b, m, deterministic)
}
func (m *ScanReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanReply.Merge(m, src)
}
func (m *ScanReply) XXX_Size() int {
	return xxx_messageInfo_ScanReply.Size(m)
}
func (m *ScanReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanReply.DiscardUnknown(m)
}

var xxx_messageInfo_ScanReply proto.InternalMessageInfo

func (m *ScanReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ScanReply) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *ScanReply) GetHostnames() []string {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

func (m *ScanReply) GetPorts() []*ScanReply_Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type ScanReply_Port struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanReply_Port) Reset()         { *m = ScanReply_Port{} }
func (m *ScanReply_Port) String() string { return proto.CompactTextString(m) }
func (*ScanReply_Port) ProtoMessage()    {}
func (*ScanReply_Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aaa3a40e8dcfc7a, []int{1, 0}
}

func (m *ScanReply_Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanReply_Port.Unmarshal(m, b)
}
func (m *ScanReply_Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanReply_Port.Marshal(b, m, deterministic)
}
func (m *ScanReply_Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanReply_Port.Merge(m, src)
}
func (m *ScanReply_Port) XXX_Size() int {
	return xxx_messageInfo_ScanReply_Port.Size(m)
}
func (m *ScanReply_Port) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanReply_Port.DiscardUnknown(m)
}

var xxx_messageInfo_ScanReply_Port proto.InternalMessageInfo

func (m *ScanReply_Port) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ScanReply_Port) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ScanReply_Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ScanRequest)(nil), "ch.guengel.nmapservice.ScanRequest")
	proto.RegisterType((*ScanReply)(nil), "ch.guengel.nmapservice.ScanReply")
	proto.RegisterType((*ScanReply_Port)(nil), "ch.guengel.nmapservice.ScanReply.Port")
}

func init() { proto.RegisterFile("nmap.proto", fileDescriptor_7aaa3a40e8dcfc7a) }

var fileDescriptor_7aaa3a40e8dcfc7a = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0xe2, 0x54, 0xe4, 0xb2, 0x9d, 0x50, 0x65, 0x45, 0x0c, 0x21, 0x08, 0x94, 0xc9,
	0x43, 0x59, 0x61, 0x61, 0x62, 0x42, 0x55, 0xba, 0x20, 0x36, 0x37, 0x3d, 0xb5, 0x48, 0x4d, 0x62,
	0x6c, 0x07, 0x89, 0x0f, 0xcc, 0xf7, 0x40, 0xb6, 0xab, 0xb4, 0x03, 0x7f, 0x36, 0xbf, 0x77, 0x7a,
	0x7a, 0x3f, 0xdf, 0x01, 0xf4, 0x9d, 0x54, 0x42, 0xe9, 0xc1, 0x0e, 0x38, 0x6f, 0x77, 0x62, 0x3b,
	0x52, 0xbf, 0xa5, 0xbd, 0x70, 0xb6, 0x21, 0xfd, 0xf1, 0xd6, 0x52, 0xf5, 0x00, 0xf9, 0xaa, 0x95,
	0x7d, 0x43, 0xef, 0x23, 0x19, 0x8b, 0x08, 0x6c, 0x37, 0x18, 0xcb, 0xa3, 0x32, 0xaa, 0xb3, 0xc6,
	0xbf, 0xb1, 0x80, 0x73, 0x35, 0x68, 0xbb, 0x52, 0xd4, 0xf2, 0xd8, 0xfb, 0x93, 0xae, 0xbe, 0x22,
	0xc8, 0x42, 0x5e, 0xed, 0x3f, 0xf1, 0x02, 0x52, 0x63, 0xa5, 0xa5, 0x43, 0x3c, 0x08, 0xbc, 0x84,
	0x4c, 0x6e, 0x36, 0x9a, 0x8c, 0x21, 0xc3, 0xe3, 0x32, 0xa9, 0xb3, 0xe6, 0x68, 0xb8, 0xa9, 0x6b,
	0xe9, 0x65, 0x47, 0x86, 0x27, 0x61, 0x3a, 0x19, 0x78, 0x0f, 0xa9, 0xeb, 0x32, 0x9c, 0x95, 0x49,
	0x9d, 0x2f, 0x6e, 0xc5, 0xcf, 0xdf, 0x10, 0x13, 0x83, 0x58, 0x0e, 0xda, 0x36, 0x21, 0x54, 0x3c,
	0x01, 0x73, 0x12, 0xe7, 0x30, 0xeb, 0xc7, 0x6e, 0x4d, 0xda, 0x83, 0xa5, 0xcd, 0x41, 0x1d, 0x79,
	0xe3, 0x53, 0x5e, 0x04, 0xe6, 0xca, 0x79, 0x12, 0x76, 0xe0, 0xde, 0x8b, 0x17, 0x60, 0xcf, 0x9d,
	0x54, 0xb8, 0x04, 0xe6, 0xaa, 0xf0, 0xfa, 0x6f, 0x10, 0xbf, 0xcc, 0xe2, 0xea, 0x5f, 0xda, 0xea,
	0xec, 0xf1, 0x06, 0x7e, 0x39, 0xcd, 0x6b, 0x7e, 0x22, 0xd6, 0x33, 0x7f, 0xc6, 0xbb, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf1, 0xeb, 0xa1, 0xbf, 0xd4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NmapClient is the client API for Nmap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NmapClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanReply, error)
}

type nmapClient struct {
	cc *grpc.ClientConn
}

func NewNmapClient(cc *grpc.ClientConn) NmapClient {
	return &nmapClient{cc}
}

func (c *nmapClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanReply, error) {
	out := new(ScanReply)
	err := c.cc.Invoke(ctx, "/ch.guengel.nmapservice.Nmap/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NmapServer is the server API for Nmap service.
type NmapServer interface {
	Scan(context.Context, *ScanRequest) (*ScanReply, error)
}

func RegisterNmapServer(s *grpc.Server, srv NmapServer) {
	s.RegisterService(&_Nmap_serviceDesc, srv)
}

func _Nmap_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NmapServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ch.guengel.nmapservice.Nmap/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NmapServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nmap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ch.guengel.nmapservice.Nmap",
	HandlerType: (*NmapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _Nmap_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nmap.proto",
}
