version: 2.1

orbs:
  c: rafaelostertag/common-orb@1.19.0

workflows:
  build-any-branch:
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "not-used"
          no-sonar: true
          no-checkout: true
          executor: c/java11-build-amd64-machine
          pre-steps:
            - checkout
            - run:
                name: Create sources
                command: ./build-java.sh
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - src
          context:
            - repository-read
      - c/maven-deploy-artifacts:
          name: deploy-maven-artifact
          filters:
            branches:
              only:
                - master
          pre-steps:
            - checkout
            - attach_workspace:
                at: .
          requires:
            - build-and-test
          context:
            - maven-repository-write
